news/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  authenticated :user do
    root 'feeds#index', as: :authenticated_root
  end

  root 'feeds#index'

  resources :feeds, except: [:edit, :update], constraints: { id: /\d+/ }
  post 'feeds/:id/refresh', to: 'feeds#refresh', as: 'refresh_feed', constraints: { id: /\d+/ }
end

news/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

news/app/models/feed.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: feeds
#
#  id                 :bigint           not null, primary key
#  completed_at       :datetime
#  is_email_on_update :boolean
#  language           :string           default("")
#  name               :string           not null
#  runned_at          :datetime
#  search_query       :string           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  grab_interval_id   :integer          not null
#  user_id            :integer          not null
#
# Indexes
#
#  index_feeds_on_created_at        (created_at)
#  index_feeds_on_grab_interval_id  (grab_interval_id)
#  index_feeds_on_user_id           (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (grab_interval_id => grab_intervals.id) ON DELETE => restrict
#  fk_rails_...  (user_id => users.id)
#
class Feed < ApplicationRecord
  belongs_to :user
  belongs_to :grab_interval
  has_many :feed_details, dependent: :destroy

  validates :name, presence: true
  validates :search_query, presence: true, length: { maximum: 60 }
  validates :grab_interval, presence: true
  validates :user, presence: true
end

news/app/models/feed_detail.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: feed_details
#
#  id           :bigint           not null, primary key
#  author       :string
#  description  :string           not null
#  published_at :datetime         not null
#  source_name  :string           not null
#  title        :string           not null
#  url          :string           not null
#  url_to_image :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  feed_id      :integer          not null
#
# Indexes
#
#  index_feed_details_on_feed_id          (feed_id)
#  index_feed_details_on_feed_id_and_url  (feed_id,url) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (feed_id => feeds.id) ON DELETE => cascade
#
class FeedDetail < ApplicationRecord
  belongs_to :feed

  validates :description, presence: true
  validates :published_at, presence: true
  validates :source_name, presence: true
  validates :title, presence: true
  validates :url, presence: true
  validates :feed, presence: true
end

news/app/models/grab_interval.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: grab_intervals
#
#  id            :bigint           not null, primary key
#  interval      :float            not null
#  name          :string           not null
#  next_start_at :datetime         not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_grab_intervals_on_interval  (interval) UNIQUE
#  index_grab_intervals_on_name      (name) UNIQUE
#
class GrabInterval < ApplicationRecord
  has_many :feeds

  validates :interval, presence: true
  validates :name, presence: true, length: { maximum: 20 }
end

news/app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string           not null
#  last_name              :string           not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  time_zone              :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  has_many :feeds, dependent: :destroy

  # Include default devise modules. Others available are:
  # :validatable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable,
         :secure_validatable

  validates :email, presence: true
  validates :first_name, presence: true, format: { with: /\A[a-z\d]*\z/i }, length: { maximum: 30 }
  validates :last_name, presence: true, format: { with: /\A[a-z\d]*\z/i }, length: { maximum: 30 }
end

news/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  around_action :switch_time_zone, if: :current_user

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name time_zone])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name time_zone])
  end

  def switch_time_zone(&block)
    Time.use_zone(current_user.time_zone, &block)
  end
end

news/app/controllers/feeds_controller.rb
# frozen_string_literal: true

class FeedsController < ApplicationController
  before_action :authenticate_user!
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  Language = Struct.new(:key, :label)

  def index
    feeds
  end

  def show
    @feed_details = feed.feed_details.order('published_at DESC').page(params[:page])
  end

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.user = current_user

    if @feed.save
      Feeds::EnqueueFeed.call(@feed.id)
      redirect_to feeds_path
    else
      render :new
    end
  end

  def destroy
    feed.destroy

    redirect_to feeds_path
  end

  def refresh
    Feeds::EnqueueFeed.call(params[:id])
    flash[:notice] = I18n.t('feeds.refresh.start')
    redirect_to feed_path
  end

  private

  def feed
    @feed ||= Feed.find(params[:id]).decorate
  end

  def feeds
    @feeds ||= current_user.feeds.all.order('created_at DESC').decorate
  end

  def feed_params
    params.require(:feed).permit(:name, :language, :search_query, :grab_interval_id, :is_email_on_update)
  end

  def record_not_found(error)
    flash.now.alert = error.message

    render 'shared/_alert'
  end
end

news/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def update
    update_params = devise_parameter_sanitizer.sanitize(:account_update)
    @user = User.find(current_user.id)

    if needs_password?
      updated = @user.update_with_password(update_params)
    else
      update_params.delete('password')
      update_params.delete('password_confirmation')
      update_params.delete('current_password')
      @user.assign_attributes(update_params)
      updated = @user.save
    end

    if updated
      set_flash_message :notice, :updated
      redirect_to edit_user_registration_path
    else
      render :edit
    end
  end

  private

  def needs_password?
    @user.email != params[:user][:email] || params[:user][:password].present?
  end
end

news/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

news/app/views/feeds/_detail.html.slim
.card.mb-3
  .card-header
    h6= link_to detail.title, detail.url, target: :_blank
  .card-body
    .row
      .col-sm-2
        img.crop src="#{detail.url_to_image}" style=("height:125px; width:125px; object-fit:cover")
      .col-sm-10
        .row
          .col-sm-2 Description:
          .col-sm-8= detail.description
        .row
          .col-sm-2 Author:
          .col-sm-8= detail.author
        .row
          .col-sm-2 Published at:
          .col-sm-8= detail.published_at
        .row
          .col-sm-2 Source name:
          .col-sm-8= detail.source_name

news/app/views/feeds/_links.html.slim
- case owner
- when 'index'
  .row
    = link_to '+Add new feed', new_feed_path, class: 'btn btn-outline-secondary'
- when 'show'
  .row
    .col-6
      h6= "Updated at: #{@feed.completed_at}"
    .col-6
      .text-right= link_to 'Force to grab news', refresh_feed_path, method: :post, class: 'btn btn-primary'

news/app/views/feeds/index.html.slim
.container
  = render 'shared/alert'
  h2.text-center Welcome to the personal News Feed website!
  hr/
  h4.mb-0.text-center The news are grabbed from https://newsapi.org/. Add new feeds and enjoy!
  = render 'links', owner: 'index'
  .row.row-cols-1.row-cols-md-3
    - @feeds.each do |feed|
      .col
        .[class = "card #{ feed.id.odd? ? 'text-white bg-secondary' : 'text-dark bg-warning' } mb-3"]
          .card-header
            .row
              .col
                h4= link_to feed.name, feed_path(feed)
              .col
                .text-right= "Since: #{feed.created_at.strftime('%b-%d-%Y %H:%M:%S')}"
          .card-body
            .row
              .col Search query:
              .col= feed.search_query
            .row
              .col Language:
              .col= feed.language_caption
            .row
              .col Notify if update:
              .col= check_box_tag 'flag', true, feed.is_email_on_update, disabled: true
            .row
              .col Updated interval:
              .col= feed.grab_interval.name
          .card-body
            = link_to "Delete", feed_path(feed), method: :delete, data: { confirm: "Are you sure?" }

news/app/views/feeds/new.html.slim
.container
.row
  .col-md-5.offset-sm-1
    h3 Creating new Feed
    = simple_form_for @feed, wrapper: :horizontal_form do |f|
      = f.input :name, autofocus: true, input_html: {class: 'col-md-7'}
      = f.input :language, collection: Languages.dataset, label_method: :label, value_method: :key, input_html: {class: 'col-md-7'}
      = f.input :search_query, input_html: {class: 'col-md-7'}
      = f.association :grab_interval, collection: GrabInterval.order('interval'), input_html: {class: 'col-md-7'}
      = f.input :is_email_on_update, as: :boolean, wrapper: :horizontal_boolean, label: '', checked_value: true, unchecked_value: false
      = f.button :submit, 'Create new feed', class: 'btn-primary'

news/app/views/feeds/show.html.slim
.container
  = render 'shared/alert'
  h3.text-center= @feed.name
  = render 'links', owner: 'show'
  = paginate @feed_details
  - @feed_details.each do |detail|
    = render 'detail', detail: detail
  = paginate @feed_details

news/app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title News
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    = render "shared/session"
    = yield

news/app/views/shared/_alert.html.slim
- flash.each do |type, msg|
  - if type == 'notice'
    .alert.alert-success
      = msg
  - if type == 'alert'
    .alert.alert-danger
      = msg

news/app/views/shared/_session.html.slim
- if user_signed_in?
  nav.navbar.fixed-top.navbar-expand-lg.navbar-light style="background-color: #e3f2fd;"
    a.navbar-brand href="#{root_path}" FEEDS
    button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.w-100
        li.nav-item.dropdown.ml-auto
          a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            | User
          .dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdown"
            = link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item'
            = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item'
  br